sonar.organization=osmanorhan
sonar.projectKey=osmanorhan_ucl-sim
sonar.projectName=Champions League Simulation
sonar.sourceEncoding=UTF-8

sonar.sources=apps/api/app,apps/web/src
sonar.tests=apps/api/tests,apps/web/src

sonar.exclusions=apps/web/src/**/*.test.ts,apps/api/vendor/**,apps/web/node_modules/**,apps/web/dist/**,apps/api/coverage/**,apps/web/coverage/**
sonar.test.inclusions=apps/api/tests/**/*.php,apps/web/src/**/*.test.ts

sonar.php.coverage.reportPaths=apps/api/coverage/clover.xml
sonar.javascript.lcov.reportPaths=apps/web/coverage/lcov.info
sonar.typescript.tsconfigPath=apps/web/tsconfig.app.json
s